### ISSUE TITLE
Création de la classe ResourceStack

### ISSUE THREAD

**Issue by McMuzzle** [BorealianStudio/OpenSpaceTycoon#11]
Il faut mettre le code en place pour les bases de la classe ResourceStack. Un ResourceStack est un groupe de RessourceElement. Il est normalement stocké soit dans un hangar soit dans un vaisseau.

Exemple cas d'utilisation : Un vaisseau qui arrive à une station et doit charger 100m3 d'eau. Il va chercher s'il existe un ResourceStack d'eau, si oui il va y prendre une quantité de ressource. Ce stack étant constitué de un ou plusieurs ResourceElement, il faudra toujours fournir les ressources les plus anciennes en priorité. Le vaisseau charge toujours ce qu'il y à de plus ancien dans la station. Le vaisseau recoit donc un ResourceStack, constitué lui aussi de 1 ou plusieurs ResourceElement, et va l'ajouter a sa cargaison. S'il existe deja un stack d'eau dans le vaisseau, les stack sont combinés, sinon il est simplement ajouté.

Prérequis : #9 
les tests pour cette fonctionnalité sont indiqués par un "issue#11", il faut supprimer les ignores pour tout ces tests avant de livrer et vous assurer du succès des tests.

**Comment by PitouGames** [comment]
J'aimerai un peux plus de précision ;
- Un ResourceStack est d'un seul type d'élément et contient différents ResourceElement de ce type => OK
- Chacun des ResourceElement possède une date de fabrication et la quantité de ressources produites à cette date => OK

Dans la fonction "public void Add(ResourceElement elem)" en commentaire il est indiqué que la quantité du ResourceElement vaut 0 suite à l'ajout dans le Stack... Le soucis est qu'ensuite on ne peux plus savoir combien d'unité ont été produites à quelle date ?

**Comment by PitouGames** [comment]
Il me semble qu'il y a un soucis de cohérence entre le test StackConstruction() et StackAdd().
Lorsqu'on ajoute un élément dans le stack avec la méthode Add(), la quantité de l'élément doit passée à 0.
Dans le test du constructeur "ResourceStack(ResourceElement elem)" après construction le test veut que elem soit à 100, or logiquement il faut vider cet élément ?

Je ne comprend pas vraiment l'utilité de devoir faire des copies d'élément dans le ResourceStack, puis de vider l'élément original.

**Comment by McMuzzle** [comment]
Effectivement, le test devrait tester sur stack, je vais corriger ca.

**Comment by McMuzzle** [comment]
L'idée de vider l'orignale évite de réutiliser la quantité ailleurs. Je ne sais pas si c'est intéressant, mais j'ai l'impression que ca réduit les risques d'erreurs.
