### ISSUE TITLE
Création de la classe ResourceElement

### ISSUE THREAD

**Issue by McMuzzle** [BorealianStudio/OpenSpaceTycoon#9]
Il faut mettre le code en place pour les bases de la classe ResourceElement. Un ResourceElement est un groupe de ressource d'un type donné qui à été produit par une station à un moment donné. En d'autre mot, quand une station produit des ressources, elle dépose un ResourceElement dans le hangar d'une société.  
Les ResourceElement sont contenue dans des ResourceStack.

Un ResourceElement peut être divisé pour permettre d'être passé du hangar vers le stockage d'un vaisseau par exemple.

les tests pour cette fonctionnalité sont indiqués par un "issue#9", il faut supprimer les ignores pour tout ces tests avant de livrer.

**Comment by PitouGames** [comment]
Je viens de proposer un pull qui devrait répondre aux attentes ;)
